### ISSUE TITLE
Loading client side react-components on the server?

### ISSUE THREAD

**Issue by jamesabbottsmith** [AdamBrodzinski/meteor-react-boilerplate#3]
Hi Adam,

Thanks for this. Whilst I've used Meteor before, this is my first time using React + Meteor. This boilerplate has generally been quiet useful to get started quickly, with just enough examples on the way through to see where to go. 

I have a question about the use of Browserify and server side rendering...

Components are defined on both the server and client, which makes sense to allow server side rendering (although I'm not using that currently), but browserify only installs react-components on the client, since its defined in client/lib/. This caused an error on the server, since the react-components did not exist there.

My particular use case is trying to get the React Drop and Drag module set up.

[client/lib/app.browserify.js]

```
DragDropContext = require('react-dnd').DragDropContext; 
HTML5Backend = require('react-dnd-html5-backend');
```

Then wrap the MainLayout component in the higher-level DragDropContext (as per their instructions).

[both/pages/MainLayout.jsx]

```
 MainLayout = DragDropContext(HTML5Backend)(MainLayout);
```

The server throws an error the 'HTML5Backend' is not defined. 

Moving these component definitions inside client/ seems to have worked though.

Have I totally missed something? 

Thanks

**Comment by AdamBrodzinski** [comment]
Yes so if you import in the both folder you need to import on the server as well. However, since serverside rendering became really expensive (in CPU) with React i've since been putting all react code in `client` instead of `both`. So keeping it in the client is just fine.

However, with Meteor 1.3 on the cusp... I would recommend using that instead of browserify. Even if you just remove browserify, and import the modules in the same file and expose globally (basically using the new module imports but making their exports global).

Ideally using ES6 modules everywhere is best but not always doable with a current project.

Hope this helps!
