### ISSUE TITLE
"Both" folder

### ISSUE THREAD

**Issue by t0dd** [AdamBrodzinski/meteor-react-boilerplate#7]
"This repo aims to get you up and running with sane defauts. Most of the content is in the 'both' folder so that we can so serverside rendering more easily."

No "both" folder available after running.  Did this change?

**Comment by AdamBrodzinski** [comment]
Ah good question. It used to use the both folder but that ends up slowing down reloads because it forces Node to restart... also serverside rendering turned out to be a huge effort and not worth it (for me at least). 

I think one of the later PRs moved it to an imports directory after 1.3... this originally started before React was integrated (I think at least). There may be better boilerplates out there but this should still be relevant. (if not PRs welcomed!)

> "This repo aims to get you up and running with sane defauts. Most of the content is in the 'both' folder so that we can so serverside rendering more easily."

Is this text somewhere in the readme? I didn't see it there.

**Comment by t0dd** [comment]
Interesting!  I haven't used Meteor since 1.0, just getting back into it.  
That text is actually what comes up on the main page when you fire up the boilerplate which I found a little confusing.

**Comment by AdamBrodzinski** [comment]
ah, got it! just pushed a fix (removed it). FWIW this repo is prob a better overview of a React project as it has some components: https://github.com/AdamBrodzinski/react-ive-meteor

Thanks again! 👍

**Comment by t0dd** [comment]
Sweet! Thx!
